### ISSUE TITLE
Profile picture orientation bug

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#16]
When taking a photo with the iPhone and using that as profile picture, the resize service will not respect the orientation of the photo.

This could be due to incompatible exif data. Could be inspected with http://regex.info/exif.cgi

**Comment by chr22** [comment]
I'll take a look at it

**Comment by chr22** [comment]
IPhones doesn't rotate images, they only use the orientation property in Exif data. And Firefox is the only browser that supports it: http://stackoverflow.com/a/27882870

Most other phones rotate the image before they save it, so that the software that is used to display it, doesn't have to rotate the image.

So we now use [Image Resizer's](http://imageresizing.net/) auto rotate function as a fix.
